image: "julia:1"

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
  JULIA_NUM_THREADS: '8'

stages:
  - build
  - test
  
build:
  stage: build
  tags:
    - 'p6000'
  script:
    - curl https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-linux-x86_64.tar.gz -o julia.tar.gz
    - unp julia.tar.gz
    - export PATH="$(pwd)/julia-1.3.0/bin:$PATH"
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg; Pkg.add(\"OrdinaryDiffEq\"); Pkg.build(\"OrdinaryDiffEq\"); using OrdinaryDiffEq"
  only:
  - master
  - tags
  - external
  - pushes

test-GPU:
  stage: test
  tags:
    - 'p6000'
  dependencies:
    - build
  variables:
    GROUP: "GPU"
  script:
    - export PATH="$(pwd)/julia-1.3.0/bin:$PATH"
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg; Pkg.add(\"CuArrays\");
                          Pkg.add(\"OrdinaryDiffEq\");
                          Pkg.test(\"DiffEqBase\"; coverage=true);"
  only:
  - master
  - tags
  - external
  - pushes
